// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bwztndqxjpgtkxpzgxci.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ3enRuZHF4anBndGt4cHpneGNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMzNzA5MjYsImV4cCI6MjA3ODk0NjkyNn0.fzHrJult0YjiKy9tXLwxnzj0ZZYgtLxF9m85zneSrtM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});